### ISSUE TITLE
Decidir Tema do Projeto

### ISSUE THREAD

**Issue by claudiohsc** [unb-mds/2023-2-Squad05#11]
## Descrição

Abrir um momento em reunião para decidir o tema do projeto em que o grupo irá trabalhar.

## Objetivo

Decidir 3 estados de interesse do Projeto Querido Diário para fazer a extração de dados por município.

## Pontos Importantes

- [x] Decidir qual informação extrair dos diários oficiais.
- [x] Como apresentar os resultados da extração.
- [x] Planejar estrutura do Gitpage do projeto.
- [x] Upar ATA de reunião.
- [x] Finalizar treinamentos.

### Links

Estados disponíveis: [acesse aqui.](https://github.com/ogecece/querido-diario/blob/3e8f847d3da5e6d34a06c1a2987121c18a77fe32/scripts/multiterritory_websites_coverage/sigpub/covered_associations.csv)

**Comment by EliasOliver21** [comment]
Ata da Sprint-01
link : [Ata de Reunião.txt](https://docs.google.com/document/d/1ysKPQzbjWMf8TVG-soQq-esjtzZxLcKGomQFohxPIJQ/edit?usp=sharing)
