### ISSUE TITLE
Criar e editar o GitHubIO (Duo)

### ISSUE THREAD

**Issue by EliasOliver21** [unb-mds/2023-2-Squad05#15]
## Descrição

Aprender a utilizar o github.io (GitHub Pages)

## Objetivo

Criar e editar o GuitHub Pages

## Pontos Importantes

- [ ] Como criar o github.io
- [ ] Como editar o github.io

**Comment by Pedrin0030** [comment]
https://docs.google.com/document/d/18mJFVxo7DMh2dS3PfJacEEhFKilBKCWDqgbL6IXHl6w/edit?usp=sharing
