### ISSUE TITLE
Criar Story Map no Figma

### ISSUE THREAD

**Issue by EliasOliver21** [unb-mds/2023-2-Squad05#16]
## Descrição

O Story Map é uma técnica de estruturação dos principais requisitos de um produto de software.

## Objetivo

- Agrupar as histórias dentro de temas e épicos e facilitar a visualização da nossa relação com a jornada do produto.
- Estruturador das entregas ([releases)].
- Engajamento do time em uma discussão produtiva.

## Pontos Importantes

- [ ] Agrupe essas atividades de forma lógica, conforme o objetivo que o usuário deseja alcançar
- [ ] Relacione os Épicos e [user stories] abaixo de cada atividade.
- [ ] Organize os Épicos e histórias por prioridade (os do topo são mais prioritários)

**Comment by claudiohsc** [comment]
Link do Story Map: [clique aqui](https://www.figma.com/file/J2Za2rOxELEpH6dsINs9yv/Story-Map-2?type=whiteboard&node-id=0%3A1&t=F1v2oFnbguWRYDgd-1)
