### ISSUE TITLE
Planilha de Conhecimentos

### ISSUE THREAD

**Issue by claudiohsc** [unb-mds/2023-2-Squad05#2]
## Descrição
Criação de uma planilha para alinhar os conhecimentos gerais de todos os integrantes.

### Tarefas a serem feitas:

- [x] Criar planilha no Google Planilhas.
- [x] Todos responderem.
- [x] Definir os treinamentos para o grupo.

### Conhecimentos Essenciais

- Git e GitHub
- Python
- Metodologias Ágeis
- Ubuntu
- Web básico
- Markdown
- Docker

**Comment by EliasOliver21** [comment]
https://docs.google.com/spreadsheets/d/1yCwhFplO0_0xQ0OigVFJzDE5meSYy6QmdlzOEoPGTbY/edit?usp=sharing
