### ISSUE TITLE
Treinamento Scrapy

### ISSUE THREAD

**Issue by EliasOliver21** [unb-mds/2023-2-Squad05#21]
## Descrição

Scrapy é um biblioteca Python para coletar dados da web de forma eficiente e escalável. O uso da biblioteca pode ser útil na coleta de dados para o projeto.

## Objetivo

O objetivo deste treinamento é familiarizar os membros da equipe com os principais conceitos e técnicas associados à biblioteca Scrapy.

## Pontos Importantes

- [x] Introdução ao Scrapy: Princípios e benefícios;
- [x] Criação de spiders e definição de regras de extração;
- [x] Utilização de seletores para extrair dados;
- [x] Gerenciamento de requisições e respostas HTTP.
 
## Critérios de Aceitação

- [x] Os participantes devem entender e compreender o conteúdo de forma rápida;
- [x] Os participantes, ao final, devem ser capazes de criar spiders para extração de dados;

**Comment by claudiohsc** [comment]
Documento do Treinamento: [clique aqui](https://docs.google.com/document/d/1WZokCGLXnVqS9TspSk43scClp-wpfsGi0eUybBTt9gw/edit?usp=sharing)
