### ISSUE TITLE
Estruturação do GitIO

### ISSUE THREAD

**Issue by EliasOliver21** [unb-mds/2023-2-Squad05#25]
## Atualização do GuitHub.io

Concluir toda parte de criação do GitHhub.io. 

## Objetivo

Com o objetivo de documentar o progresso do projeto de MDS, utilizaremos o GitHub.io que servirá como uma forma de registro do trabalho, que será atualizado ao decorrer do projeto iniciado.

## Pontos Importantes:

- [x] Criação de um Branche para GitHub.io;
- [x] Atualização do servidor do MkDocs utilizado;
- [x] Construção da primeira etapa do MkDocs.

**Comment by Pedrin0030** [comment]
https://docs.google.com/document/d/18mJFVxo7DMh2dS3PfJacEEhFKilBKCWDqgbL6IXHl6w/edit?usp=sharing
