### ISSUE TITLE
Revisão: Story Map (duo)

### ISSUE THREAD

**Issue by EliasOliver21** [unb-mds/2023-2-Squad05#38]
## Descrição

Esta issue visa a criação de um Story Map, uma ferramenta visual que ajuda a mapear a jornada do usuário em nosso produto.

## Objetivo

O objetivo principal é criar um Story Map eficaz que represente a experiência do usuário de ponta a ponta, identificando suas necessidades e desafios.

## Pontos Importantes

- [x] Compreender os conceitos fundamentais do Story Map.
- [x] Coletar informações relevantes sobre a jornada do usuário.
- [x] Organizar os elementos-chave em um mapa coerente.
- [x] Identificar pontos de dor e oportunidades para melhorias.
- [x] Colaborar efetivamente para desenvolver um Story Map completo.

## Critérios de Aceitação

- [x] Ter um Story Map que represente claramente a jornada do usuário.
- [x] Propor pelo menos duas melhorias para a jornada do usuário.
- [x] Apresentar o Story Map e suas conclusões à equipe de desenvolvimento.

**Comment by claudiohsc** [comment]
Link para o Story Map completo: [clique aqui](https://www.figma.com/file/J2Za2rOxELEpH6dsINs9yv/Story-Map-2?type=whiteboard&node-id=0%3A1&t=Yw9sF00kxTJdTAzv-1)
