### ISSUE TITLE
Revisão: Protótipo no Figma

### ISSUE THREAD

**Issue by EliasOliver21** [unb-mds/2023-2-Squad05#39]
## Descrição

Revisar a funcionalidade e apresentação do site feito no Figma para a apresentação da primeira release para o dia 26 

## Objetivo

Revisar para ver se todas as coisas que foram implementadas foram devidamente colocadas e que se precisa de mais algum refinamento

## Pontos Importantes

- [x] Estar com todas as coisas que formam implemantadas funcionando como deveriam
- [x] Ter todas as funcionalidades mínimas requeridas

## Critérios de Aceitação

- [x] Estar pronto até a data limite

**Comment by claudiohsc** [comment]
Link para o Protótipo: [clique aqui](https://www.figma.com/proto/ePZs0RjH5fIwAEfHEgpJg0/MDS---Prot%C3%B3tipo?node-id=5-27&starting-point-node-id=5%3A27)
