### ISSUE TITLE
Revisão: Git Pages do Projeto

### ISSUE THREAD

**Issue by EliasOliver21** [unb-mds/2023-2-Squad05#43]
## Descrição

Restruturar toda página do Git-Pages.

## Objetivo

Reconstruir o layout da página e adicionar uma documentação melhor sobre todo projeto.
## Pontos Importantes

- [x] Adicionar pontos importantes como issues, arquitetura, tecnologia utilizada, etc; 
- [x] Ter todo projeto documentado na página.

## Critérios de Aceitação

- [x] Estar pronto até a data da release 1, para apresentação.

**Comment by claudiohsc** [comment]
Adicionei o template que estava faltando.
