### ISSUE TITLE
Reeditar protótipo do figma

### ISSUE THREAD

**Issue by EliasOliver21** [unb-mds/2023-2-Squad05#45]
## Edição do Protótipo no Figma

Para ter uma interface mais legível e melhor visualmente para nossas Personas, reestruturamos o a interface afim de torna-la melhor.

## Objetivo

Colocar as cores padrões do projeto e deixar melhor visualmente.

## Pontos Importantes

- [x] Criação de um menu;
- [x] Mudança das cores;
- [x] Padronização das páginas.

## Critérios de Aceitação

- [x] Buscar um protótipo menos poluído possível;
- [x] Padronizado.

**Comment by Pedrin0030** [comment]
Protótipo alterado https://www.figma.com/file/ePZs0RjH5fIwAEfHEgpJg0/MDS---Prot%C3%B3tipo?type=design&node-id=0-1&mode=design&t=K9R5yq2Q6ZR7yAWs-0
