### ISSUE TITLE
Definir dado a ser extraído e fazer filtragem salvando-o como Json(duo)

### ISSUE THREAD

**Issue by EliasOliver21** [unb-mds/2023-2-Squad05#46]
## Descrição

Nessa issue esperamos realizar uma filtragem de trechos que tenham o nosso dado a ser explorado. Faremos por meio de Regex.

## Objetivo

Fazer filtragem dos DOU's com Regex em busca de dados para o nosso projeto.

## Pontos Importantes

- [x] Varrer vários DOU's em txt;
- [x] Utilizar Regex na busca;
- [x] Separar trechos em um arquivo de texto;
- [x] Separar dado em um arquivo JSON.

## Critérios de Aceitação

- [x] Utilização do Regex;
- [x] Documentação do código;
- [x] Aprovação dos membros.

**Comment by claudiohsc** [comment]
Documentação Regex em Python: [clique aqui](https://docs.python.org/pt-br/dev/library/re.html#re-syntax)
