### ISSUE TITLE
Deixar Json no formato Correto e Testar Script para decidir qual período de filtragem

### ISSUE THREAD

**Issue by EliasOliver21** [unb-mds/2023-2-Squad05#68]
## Descrição

Alterar script para exportar os Json's por município, porém agora com valores somados corretos e organizados com data.

## Objetivo

Melhorar exportação em formato Json.

## Pontos Importantes

- [x] Incluir data e nome do município;
- [x] Deixar divido por linhas;
- [x] Soma dos valores.

## Critérios de Aceitação

- [x] Dados de todos os municípios do período filtrados.
- [x] Incluir categoria de Crédito Suplementar.

**Comment by claudiohsc** [comment]
Códigos alterados estão na branch "dev".
