### ISSUE TITLE
Treinamento web básico 

### ISSUE THREAD

**Issue by VictorGCOSTA** [unb-mds/2023-2-Squad05#7]
## Descrição

Treinamento para todos os membros de web básico

## Objetivo

Dominar os principais conceitos sobre desenvolvimento web

## Pontos Importantes

- [x] FrontEnd
- [x] BackEnd
- [x] API
- [x] Banco de Dados

**Comment by claudiohsc** [comment]
Boa, depois tenta deixar no padrão da Issue.
